Metrics
intuit-data-os/argo-events pull request #27
Opened 2023-03-30 19:41 UTC by antoniosi

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

2023-03-30 20:17 UTC, dfarr commented
Nice! Mind running `make lint` and committing the change? I think it's just ordering of imports that's causing that failure.

Is there any drawback to including this? I'm wondering if it's not something everyone is going to want could it be opt-in?

2023-03-30 20:40 UTC, AalokAhluwalia approved these changes

2023-03-30 20:55 UTC, dfarr requested changes
Just need to fix linting

2023-03-31 18:31 UTC, dfarr approved these changes

2023-06-14 02:26 UTC, closed without merging